language: php
php:
- '5.6'
- '7.0'
- '7.1'
install:
- ant clean
- ant build
script:
- ant test
before_deploy:
- ant statistics
- wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar
- php coveralls.phar -v
- tar -zcvf build/phpdox.tar.gz build/phpdox
- tar -zcvf build/coverage.tar.gz build/coverage
deploy:
  provider: releases
  api_key: OAu9nN4q5BUkxQKGt27tmCLAzRLxIjo3jee0H8mccQevJ3AeSQXZIRtplB1G1m+M09CAEfrwHREY2hkLUwZB0Xslkbh3+zuyTcFTzfJ1BretIHavKPnlWqrXS2xES2I0m0ddEMCj3o81lN53tBDUNSQov+E7BJumb7jAW/xC8iLujxtopLePVp1YYCBAWhsxQAmfyZmGBHu3KSrL1inmWYQLeB55Y1yTJKuDnNabGRZSUBAWkgTg5dLVxtoRCpKWOORGKm6JDRVmf8wCFFuXR+EaohbOPEFzb2p1pNmClcfd8ndiV+BZjMZiyLFZ1UpSJqIWOG1YoDIfL7JKSelF+4t6GC9KfN3TaOm06+ycIqCO/wcjf/1K+xPvcyBcbKF1CUt16CDCIGXRAQ0oa6P6Zv2CJAh0YBB+Dng7m8qWfI/95DpfOgtdiY9dtVsuKaj6OVcByL3emtOTXCd4685FpfToE2bsVv/ssP1+q7+Zxz/aIVbd/F1BemeMgDScA8/EEgmLsghj/03b4wYch7+dDMM7SP7EHHosnQ0lU3QWWtWTkMUCK9Cf6GyKwdwv/GF5JTlx0nFkKFaxPIeeo5vO9d8alfOvJndWnZ86DXr4BoN781lw4rOLfA3j+p6AzxUkGZ44PfYb1+Oz720ovMoyAt9U+dRU/qXt81A9R5Urvb8=
  file:
  - build/gitlab-client.phar
  skip_cleanup: true
  on:
    tags: true