language: php
php:
  - '5.6'
  - '7.0'
  - '7.1'
install:
  - ant clean
  - ant build
script:
  - ant test
after_success:
  - ant statistics
  - https://github.com/satooshi/php-coveralls/releases/download/v1.0.0/coveralls.phar
  - php coveralls.phar -v
deploy:
  provider: releases
  api_key:
    secure: 890f018b3a139f9e2dae6e3f51ee2471766395aa
  file: build/gitlab-client.phar
  on:
    tags: true