language: php
php:
  - '5.6'
  - '7.0'
  - '7.1'
install:
  - ant clean
  - ant build
script:
  - ant test
deploy:
  provider: releases
  api_key:
    secure: 890f018b3a139f9e2dae6e3f51ee2471766395aa
  file: build/gitlab-client.phar
  on:
    tags: true